# great-side-shop
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TECHNOLINE - Ecommerce Site</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            background: #121212;
            color: #f1f1f1;
            text-align: center;
        }
        .container {
            opacity: 0;
            transform: translateY(20px);
            transition: opacity 1s ease-out, transform 1s ease-out;
        }
        .visible {
            opacity: 1;
            transform: translateY(0);
        }
        h1 {
            font-size: 3rem;
            letter-spacing: 2px;
            text-transform: uppercase;
            animation: glow 2s infinite alternate;
            color: #ff00ff;
        }
        @keyframes glow {
            from { text-shadow: 0 0 10px #ff00ff, 0 0 20px #ff00ff, 0 0 30px #ff00ff; }
            to { text-shadow: 0 0 20px #fff, 0 0 30px #ff1493, 0 0 40px #ff1493; }
        }
        .product {
            margin: 20px auto;
            padding: 20px;
            background: rgba(255, 255, 255, 0.1);
            border-radius: 10px;
            width: 80%;
            box-shadow: 0 4px 10px rgba(255, 0, 255, 0.3);
            transition: transform 0.3s ease-in-out;
        }
        .product:hover {
            transform: scale(1.05);
        }
        select, button {
            padding: 12px;
            margin: 10px;
            font-size: 1rem;
            background: #333;
            color: #ff00ff;
            border: 1px solid #ff00ff;
            border-radius: 5px;
            cursor: pointer;
        }
        button {
            background: #ff00ff;
            color: white;
        }
        button:hover {
            background: #ff1493;
        }
        .contact-us {
            position: fixed;
            bottom: 20px;
            right: 20px;
            width: 60px;
            height: 60px;
            background: #ff00ff;
            color: white;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 1.2rem;
            text-decoration: none;
            box-shadow: 0 4px 10px rgba(255, 0, 255, 0.3);
            transition: transform 0.3s ease-in-out;
        }
        .contact-us:hover {
            transform: scale(1.1);
            background: #ff1493;
        }
    </style>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const sections = document.querySelectorAll(".container");
            const observer = new IntersectionObserver(entries => {
                entries.forEach(entry => {
                    if (entry.isIntersecting) {
                        entry.target.classList.add("visible");
                    }
                });
            }, { threshold: 0.2 });
            sections.forEach(section => observer.observe(section));
        });
        function redirectToWhatsApp(selectId) {
            const selectedOption = document.getElementById(selectId).value;
            const phone = "+918101582919";
            const message = encodeURIComponent(`Send your document for: ${selectedOption}`);
            window.location.href = `https://wa.me/${phone}?text=${message}`;
        }
    </script>
</head>
<body>
    <div class="container">
        <h1>TECHNOLINE</h1>
        <h2>- A Ecommerce site of GREAT SIDE Co. LTD -</h2>
        <p>Your onestop destination for YOUR SOLUTION</p>
    </div>
    <div class="container product">
        <h2>OUR SERVICES</h2>
        <h3>MICROSOFT WINDOWS</h3>
        <select id="windowsOptions">
            <option value="WINDOWS 10 INSTALLATION">WINDOWS 10 INSTALLATION</option>
            <option value="WINDOWS 11 INSTALLATION">WINDOWS 11 INSTALLATION</option>
            <option value="WINDOWS 10 ACTIVATION">WINDOWS 10 ACTIVATION</option>
            <option value="WINDOWS 11 ACTIVATION">WINDOWS 11 ACTIVATION</option>
        </select>
        <button onclick="redirectToWhatsApp('windowsOptions')">GET NOW</button>
    </div>
    <div class="container product">
        <h3>MICROSOFT OFFICE</h3>
        <select id="officeVersion">
            <option value="2016">2016</option>
            <option value="2019">2019</option>
            <option value="2021">2021</option>
            <option value="2024">2024</option>
        </select>
        <select id="officeType">
            <option value="STANDARD">STANDARD</option>
            <option value="PROFESSIONAL +">PROFESSIONAL +</option>
        </select>
        <button onclick="redirectToWhatsApp('officeVersion')">GET NOW</button>
    </div>
    <div class="container product">
        <h2>OUR OFFLINE SERVICE</h2>
        <h3>PRINTING OR PHOTOCOPY</h3>
        <p>Upload your files and photos via clicking on UPLOAD NOW</p>
        <select id="printingOptions">
            <option value="PHOTOCOPY">PHOTOCOPY</option>
            <option value="PRINTING">PRINTING</option>
        </select>
        <button onclick="redirectToWhatsApp('printingOptions')">UPLOAD NOW</button>
    </div>
    <div class="container product">
        <h3>OTHER SERVICES</h3>
        <select id="otherServices">
            <option value="PC BUILDING">PC BUILDING</option>
            <option value="PC ITEM RECOMENDER">PC ITEM RECOMENDER</option>
            <option value="LAPTOP / PHONE / PC SOFTWARE ISSUE RESOLVING">LAPTOP / PHONE / PC SOFTWARE ISSUE RESOLVING</option>
        </select>
        <button onclick="redirectToWhatsApp('otherServices')">GET NOW</button>
    </div>

    <!-- New Government Services section -->
    <div class="container product">
        <h3>GOVERNMENT SERVICES</h3>
        <select id="governmentServices">
            <option value="PAN CARD APPLY">PAN CARD APPLY</option>
            <option value="ADHAR CARD APPOINTMENT">ADHAR CARD APPOINTMENT</option>
            <option value="WB BIRTH CERTIFICATE APPLY">WB BIRTH CERTIFICATE APPLY</option>
            <option value="DRIVING LICENSE APPLY">DRIVING LICENSE APPLY</option>
            <option value="TRAIN/FLIGHT BOOKING">TRAIN/FLIGHT BOOKING</option>
        </select>
        <button onclick="redirectToWhatsApp('governmentServices')">GET NOW</button>
    </div>
    <!-- Contact us button now redirects to contact.html -->
    <a class='contact-us' href='/contact'>📞</a>
</body>
</html>
